development:
  adapter: mysql2
  database: Deal_A_Day
  pool: 20
  encoding: utf8
  username: root
  password: 'bela123'
  host:  localhost

test:
  adapter: mysql2
  database: Deal_A_Day_Test
  pool: 20
  encoding: utf8
  username: root
  password: 'bela123'
  host:  localhost

production:
  adapter: mysql2
  database: Deal_A_Day
  pool: 20
  encoding: utf8
  username: root
  password: bela123
  host:  mydomain.com
