# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86ea164b708a19238746d3392d3922954e78675bfd56ccbb601ffa9597283a4a0e99fdc4da10b68b168b5578a55dcbde38ed6dba2ee31cd58457400c52841843

test:
  secret_key_base: abbcf659c6c0422c54a11417b380d818e72b4574fcc347548d5dc8f97f5a40faa1e5bc718ab5b32b2a7db009f9df6b5d3173d88c598bc3eb66574d71ce0effd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
